config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  resources :books
  patch "/books/:id/reserve", to: "books#reserve", as: "reserve"
  patch "/books/:id/anti_reserve", to: "books#anti_reserve", as: "anti_reserve"
  patch "/books/:id/buy", to: "books#buy", as: "buy"
  patch "/books/:id/anti_buy", to: "books#anti_buy", as: "anti_buy"
  root "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user, optional: true

    enum status: [:available, :reserved, :purchased, :deleted]

end

app/models/user.rb
class User < ApplicationRecord

  has_many :books

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy reserve anti_reserve buy anti_buy ]

  # GET /books or /books.json
  def index
    @books = Book.where(status: :available)
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reserve
    respond_to do |format|
      if @book.update!(status: 1, user: current_user)
        format.js { render nothing: true, notice: 'Book (libro) fue reservado.' }
      end
    end
  end

  def anti_reserve
    respond_to do |format|
      if @book.update!(status: 0, user: nil)
        format.js { render nothing: true, notice: 'Book (libro) fue desreservado.' }
      end
    end
  end

  def buy
    respond_to do |format|
      if @book.update!(status: 2, user: current_user)
        format.js { render nothing: true, notice: 'Book (libro) fue comprado.' }
      end
    end
  end

  def anti_buy
    respond_to do |format|
      if @book.update!(status: 3, user: current_user)
        format.js { render nothing: true }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :status, :isbn)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
    @books = @user.books.reserved
    @purchased = @user.books.purchased
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<tr id="book-<%=book.id%>">
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.status %></td>
    <td><%= book.isbn %></td>
    <td><%= link_to 'Borrar', anti_buy_path(book.id), method: :patch, remote: true %></td>
</tr>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/anti_buy.js.erb
$('#book-<%=@book.id%>').remove();
alert('igual tean a pillarte')

app/views/books/anti_reserve.js.erb
$('#book-<%=@book.id%>').remove();

app/views/books/buy.js.erb
$('#book-<%=@book.id%>').remove();
$('#purchased').append('<%= escape_javascript(render(:partial => "books/book", :locals => {:book => @book})) %>');

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th>Isbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr id="book-<%=book.id%>">
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= book.isbn %></td>
        <td><%= link_to 'Reserve', reserve_path(book.id), method: :patch, remote: true %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/reserve.js.erb
$('#book-<%=@book.id%>').remove();

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E47Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservados</h1>

<table class="table table-striped table-">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th>Isbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr id="book-<%=book.id%>">
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= book.isbn %></td>
        <td><%= link_to 'desreservar', anti_reserve_path(book.id), method: :patch, remote: true %></td>
        <td><%= link_to 'Comprar', buy_path(book.id), method: :patch, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Comprados</h1>

<table class="table table-striped table-">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th>Isbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="purchased">
    <% @purchased.each do |book| %>
      <tr id="book-<%=book.id%>">
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= book.isbn %></td>
        <td><%= link_to 'Borrar', anti_buy_path(book.id), method: :patch, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>